In [5]:
import numpy as np
# import np softmax


def softmax(x,dim=-1):
    max_value = np.max(x, axis=dim, keepdims=True) # L,L,1
    exp_x = np.exp(x - max_value) # L,L,64
    sum_exp_x = np.sum(exp_x, axis=dim, keepdims=True) # L,L,1
    y = exp_x / sum_exp_x
    return y

In [7]:
logits = np.random.randn(10, 10, 64)
probs = softmax(logits)

In [2]:
num_res = 100
clipped_num_res = np.maximum(num_res, 19)
d0 = 1.24 * (clipped_num_res - 15) ** (1. / 3) - 1.8

In [3]:
probs = softmax(logits, axis=-1)

3.6520687934761424

In [17]:
num_bins = 64
max_erroe_bin = 31
breaks = np.linspace(
    0., max_erroe_bin, num_bins - 1)
print(f"shape of breaks: {breaks.shape}")

shape of breaks: (63,)


In [22]:
breaks

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. ])

In [23]:
# Add half-step to get the center
step = (breaks[1] - breaks[0])

bin_centers = breaks + step / 2
# Add a catch-all bin at the end.
bin_centers = np.concatenate([bin_centers, [bin_centers[-1] + step]], axis=0)
print(f"shape of bin_centers: {bin_centers.shape}")

shape of bin_centers: (64,)


In [24]:
tm_per_bin = 1. / (1 + np.square(bin_centers) / np.square(d0))

In [25]:
tm_per_bin

array([0.99533586, 0.95953268, 0.89513498, 0.81326341, 0.72486572,
       0.63815974, 0.55805636, 0.48677207, 0.4247631 , 0.37151997,
       0.326102  , 0.28744776, 0.25453396, 0.22644452, 0.20239127,
       0.181711  , 0.16385245, 0.1483603 , 0.13485937, 0.12304053,
       0.1126486 , 0.10347242, 0.09533664, 0.08809509, 0.08162545,
       0.07582489, 0.07060666, 0.06589723, 0.06163401, 0.05776354,
       0.05423994, 0.05102372, 0.04808075, 0.04538143, 0.04289997,
       0.04061389, 0.03850347, 0.03655139, 0.03474239, 0.03306297,
       0.03150119, 0.03004641, 0.02868919, 0.02742106, 0.02623447,
       0.02512263, 0.02407944, 0.02309942, 0.02217759, 0.02130948,
       0.02049102, 0.01971852, 0.01898862, 0.01829826, 0.01764467,
       0.01702528, 0.01643777, 0.01587999, 0.01534999, 0.01484595,
       0.01436623, 0.01390928, 0.01347369, 0.01305816])

In [26]:
predicted_tm_term = (probs * tm_per_bin).sum(-1)

In [29]:
predicted_tm_term

array([[0.17909932, 0.13737669, 0.13910296, 0.20424332, 0.18515297,
        0.16306545, 0.11202117, 0.1886261 , 0.09910108, 0.12296503],
       [0.16261438, 0.13685217, 0.22500003, 0.15073002, 0.11990103,
        0.13959428, 0.27484976, 0.19616335, 0.18352049, 0.16465732],
       [0.14050972, 0.14503962, 0.20609101, 0.1609441 , 0.17526215,
        0.15210211, 0.17087797, 0.157245  , 0.18063095, 0.16212134],
       [0.16786577, 0.14108027, 0.17747104, 0.1584792 , 0.12834079,
        0.1337216 , 0.15207327, 0.19736005, 0.16072999, 0.13876611],
       [0.19882685, 0.13654155, 0.1657041 , 0.12641982, 0.15063186,
        0.17960611, 0.23343011, 0.13878014, 0.19478265, 0.34596958],
       [0.22933886, 0.19822161, 0.16741908, 0.27077525, 0.12892025,
        0.17194365, 0.09649993, 0.11559974, 0.13711364, 0.16050262],
       [0.19800563, 0.11878168, 0.1680873 , 0.12567987, 0.22756437,
        0.17839462, 0.21572045, 0.22786635, 0.15119701, 0.10604766],
       [0.12863794, 0.2290285 , 0.1645150